### ISSUE TITLE
Frontend: Add logged in user to browsers session cache (JSON web token when authentication is done)

### ISSUE THREAD

**Issue by Miska-Mynttinen** [Miska-Mynttinen/software-engineering-2-course-project#29]
Use this JSON web token and the username in the system to be the current user when creating or editing elements (Repository, Pipeline, Operator or Resource).

**Comment by Miska-Mynttinen** [comment]
Javascript has session storage and local storage. Use session storage.

**Comment by yahyacph** [comment]
I uploaded the implementation to the users-username branch. plz let met know if there is any issue.
