### ISSUE TITLE
Frontend: Sending a login request to the backend and receiving the returned bearer token

### ISSUE THREAD

**Issue by Miska-Mynttinen** [Miska-Mynttinen/software-engineering-2-course-project#9]
In the Frontends api file implement a new API call that request the backend for login authorization when the user logs in.

Then store the returned login bearer token to the browsers localStorage.

Check the browsers localStorage for the token automatically when starting the app to see if user needs to login.

**Comment by tamasarker1434** [comment]
They need to be in the backendAPI.tsx file. 

/authentication/login should be a POST request with the username and password in the body. It should return the JSON web token from succesful login. 

/authentication/logout should be a DELETE request that deletes the token from the system.

/authentication/checkToken could be a GET request that checks that the token is in the system, is valid and is related to the current user.
